name: build-python3-image
on:
  push:
    branches:
      - master
    paths:
      - 'judges/python3/*'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v1.0.1
        with:
          repository: pnoj/python3
          path: judges/python3
          add_git_labels: true
          tag_with_sha: true
          tags: latest
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
